## Numpy Arrays

In [2]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#A range - creating an array using a range

In [10]:
np.arange(0,11,2) #Takes a range from 0 to 10 with steps of 2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#Getting a 1-D zero vector
np.zeros(3)

array([0., 0., 0.])

In [14]:
#The first number sd no of Rows and the Second is Columns
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#Linspace like a range, takes evenly spaced points between your start and end
#np.linspace(start, End, No of points to return)

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
#Getting an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])